from enum import StrEnum


class RunStatus(StrEnum):
    CREATED = "CREATED"
    INSPECTED = "INSPECTED"
    AUDIO_READY = "AUDIO_READY"
    TRANSCRIBED = "TRANSCRIBED"
    ANALYZED = "ANALYZED"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    REVIEWED = "REVIEWED"
    RENDERED = "RENDERED"
    COMPLETED = "COMPLETED"
    FAILED_INSPECT = "FAILED_INSPECT"
    FAILED_AUDIO = "FAILED_AUDIO"
    FAILED_TRANSCRIPTION = "FAILED_TRANSCRIPTION"
    FAILED_ANALYSIS = "FAILED_ANALYSIS"
    FAILED_RENDER = "FAILED_RENDER"
