"""Domain models for the preview stage (CE-034).

A preview is a throwaway proxy, but the record of one is not. It is what lets a
later invocation answer "are the files in this directory still the previews of
this shortlist" without re-encoding anything, and what lets a reviewer trust
that the clip they are watching is the interval the candidate claims.

Two ideas shape the shapes here, and both are borrowed from ``candidates.py``
because they earned their keep there.

**A record describes a file that exists.** Every field of ``PreviewRecord`` is
measured after the encode: the dimensions and the duration come from ffprobe
reading the finished file, the digest and the size from the bytes on disk. None
of them is the value that was *requested*, because a record of what was
requested proves nothing about what was produced.

**The index is validated against itself.** The declared duration has to match
the interval, the filename has to name the candidate it belongs to, the
measured duration has to be close to the interval it claims, and no preview may
reach past the end of the source. A set of previews that cannot pass those
checks is not reused, and the alternative to checking is a reviewer watching
the wrong seconds of video.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import Field, model_validator

from content_engine.domain.candidates import _Artifact, _close

#: Bumped whenever previews/index.json changes incompatibly.
PREVIEW_INDEX_SCHEMA_VERSION = 1
#: Bumped whenever the preview policy changes what a preview contains. Lives
#: here rather than beside the rules because the index carries it as a default,
#: and ``preview_rules`` imports these models.
PREVIEW_RULES_VERSION = 1
#: Bumped whenever previews/config.effective.json changes incompatibly.
PREVIEW_STAGE_CONFIG_SCHEMA_VERSION = 1

#: How a preview file is named, and the whole of the naming rule. The candidate
#: identifier is the only variable part, which is what makes the mapping from a
#: file back to a candidate total and reversible.
PREVIEW_FILENAME_TEMPLATE = "candidate_{candidate_id}.mp4"

#: Characters a candidate identifier may contain before it is put in a path.
#: Identifiers are generated by CE-024 as ``cand_`` plus hex, so this never
#: rejects anything the engine produced; it rejects what an edited artifact
#: could contain. A filename is a path, and a path assembled from an untrusted
#: string is a traversal waiting to happen.
_SAFE_IDENTIFIER = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")

#: A measured duration is compared to the interval it claims to hold, never
#: equated to it: the encoder ends on a frame boundary and the muxer rounds.
#: One second is far tighter than any interval this engine proposes and far
#: looser than the error a correct encode accumulates.
PREVIEW_DURATION_TOLERANCE_SECONDS = 1.0


def preview_filename(candidate_id: str) -> str:
    """The file one candidate's preview is written to, or a refusal.

    Raises rather than sanitising. A candidate identifier that is not safe to
    put in a path did not come from this engine, and quietly rewriting it would
    map two different candidates onto one file.
    """
    if not candidate_id or not set(candidate_id) <= _SAFE_IDENTIFIER:
        raise ValueError(
            f"candidate identifier {candidate_id!r} is not safe to use in a filename; "
            "expected only letters, digits, underscores and hyphens"
        )
    return PREVIEW_FILENAME_TEMPLATE.format(candidate_id=candidate_id)


class PreviewStageConfig(_Artifact):
    """``previews/config.effective.json``: what the preview stage really ran.

    The readable counterpart of the stage fingerprint, following the shape
    transcription and analysis already use (ADR-017). The fingerprint decides
    whether a preview set may be reused; this explains why, in terms a person
    can read without reversing a digest.

    The encoder settings are constants of this stage rather than configuration
    keys. ADR-028 has the reasoning: a preview is a proxy nobody publishes, its
    encoder parameters are not an experiment variable, and putting them in
    ``[preview]`` would have folded them into ``config_sha256`` -- changing the
    logical identity of every existing experiment to describe a throwaway file.
    They are recorded here in full regardless, because the stage still has to be
    able to say what produced its output.

    Nothing here names a path, a machine or a credential, so the artifact is
    comparable across machines and safe to attach to a report.
    """

    schema_version: int = PREVIEW_STAGE_CONFIG_SCHEMA_VERSION

    width: int = Field(gt=0)
    height: int = Field(gt=0)
    #: How the source frame is fitted into those dimensions. One value today;
    #: named rather than implied so CE-043's presets cannot be confused with it.
    scaling: str = Field(min_length=1)
    pad_color: str = Field(min_length=1)

    video_codec: str = Field(min_length=1)
    encoder_preset: str = Field(min_length=1)
    crf: int = Field(ge=0, le=51)
    pixel_format: str = Field(min_length=1)

    audio_codec: str = Field(min_length=1)
    audio_bitrate: str = Field(min_length=1)
    audio_sample_rate: int = Field(gt=0)
    audio_channels: int = Field(gt=0)

    #: What ffprobe must report for a preview to be accepted, which is not the
    #: same string as the encoder that produced it: libx264 writes h264.
    expected_video_codec: str = Field(min_length=1)
    expected_audio_codec: str = Field(min_length=1)
    duration_tolerance_seconds: float = Field(gt=0)

    preview_rules_version: int
    #: Bumped independently of the rules: the same policy can be expressed by a
    #: different argument list, and an argument list change alters the bytes.
    argument_version: int
    index_schema_version: int
    #: The candidate schema these previews were cut from, so a preview set can
    #: never be read as though it described a different generation of shortlist.
    candidates_schema_version: int

    @model_validator(mode="after")
    def validate_dimensions(self) -> PreviewStageConfig:
        for name, value in (("width", self.width), ("height", self.height)):
            if value % 2 != 0:
                raise ValueError(f"preview {name} ({value}) must be even for H.264 encoding")
        return self


class PreviewRecord(_Artifact):
    """One preview file, as measured after it was produced."""

    candidate_id: str = Field(min_length=1)
    #: The candidate's rank, so the review order is readable from the index
    #: alone rather than recovered by joining against candidates.json.
    rank: int = Field(ge=1)
    start: float = Field(ge=0)
    end: float = Field(gt=0)
    duration: float = Field(gt=0)
    filename: str = Field(min_length=1)
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    #: What ffprobe read back off the finished file.
    measured_duration_seconds: float = Field(gt=0)
    video_codec: str = Field(min_length=1)
    #: Null only for a source that had no audio track, which the inspect stage
    #: already refuses; kept optional so the record cannot invent one.
    audio_codec: str | None = None
    sha256: str = Field(min_length=64, max_length=64)
    size_bytes: int = Field(gt=0)

    @model_validator(mode="after")
    def validate_record(self) -> PreviewRecord:
        if self.end <= self.start:
            raise ValueError(
                f"preview for {self.candidate_id} ends at {self.end}, at or before its start"
            )
        if not _close(self.duration, self.end - self.start):
            raise ValueError(
                f"preview for {self.candidate_id} declares duration {self.duration} for the "
                f"interval [{self.start}, {self.end}]"
            )
        if self.filename != preview_filename(self.candidate_id):
            raise ValueError(
                f"filename {self.filename!r} does not name candidate {self.candidate_id}"
            )
        drift = abs(self.measured_duration_seconds - self.duration)
        if drift > PREVIEW_DURATION_TOLERANCE_SECONDS:
            raise ValueError(
                f"preview for {self.candidate_id} measured {self.measured_duration_seconds}s "
                f"for a {self.duration}s interval, {drift:.3f}s beyond the "
                f"{PREVIEW_DURATION_TOLERANCE_SECONDS}s tolerance"
            )
        return self


class PreviewIndex(_Artifact):
    """``previews/index.json``: every preview this run holds, and what it is.

    Carries the identity of what it was cut from -- the analysis fingerprint and
    the source digest -- rather than a path. A path says where the file was on
    one machine; the digest says whether it is the same file.
    """

    schema_version: int = PREVIEW_INDEX_SCHEMA_VERSION
    rules_version: int = PREVIEW_RULES_VERSION
    generated_at: datetime
    #: The analysis execution these previews belong to. One value, checked
    #: rather than trusted: a preview set moved from another run would be
    #: internally consistent and completely wrong.
    analysis_fingerprint: str = Field(min_length=64, max_length=64)
    source_sha256: str = Field(min_length=64, max_length=64)
    source_duration_seconds: float = Field(gt=0)
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    previews: list[PreviewRecord] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_index(self) -> PreviewIndex:
        identifiers = [entry.candidate_id for entry in self.previews]
        repeated = sorted({name for name in identifiers if identifiers.count(name) > 1})
        if repeated:
            raise ValueError(f"candidate appears more than once: {', '.join(repeated)}")

        ranks = [entry.rank for entry in self.previews]
        if ranks != list(range(1, len(ranks) + 1)):
            raise ValueError(f"preview ranks are not contiguous from 1: {ranks}")

        for entry in self.previews:
            if (entry.width, entry.height) != (self.width, self.height):
                raise ValueError(
                    f"preview for {entry.candidate_id} is {entry.width}x{entry.height} in an "
                    f"index of {self.width}x{self.height} previews"
                )
            if entry.end > self.source_duration_seconds + PREVIEW_DURATION_TOLERANCE_SECONDS:
                raise ValueError(
                    f"preview for {entry.candidate_id} ends at {entry.end}, beyond the source "
                    f"duration ({self.source_duration_seconds})"
                )
        return self

    @property
    def by_candidate(self) -> dict[str, PreviewRecord]:
        return {entry.candidate_id: entry for entry in self.previews}
