"""Domain models for the final render stage (CE-045, CE-046).

The preview stage's models earned two ideas that apply here unchanged, and one
that does not.

**A record describes files that exist.** Dimensions, sample aspect ratio,
codecs and duration come from ffprobe reading the finished MP4; the digests and
sizes come from the bytes of all three artifacts. Nothing here is a value that
was *requested*, because a record of what was requested cannot notice that
FFmpeg quietly did something else.

**The index is validated against itself.** A declared duration must be its own
interval, a directory must name its own candidate, a clip must not reach past
the source, and no two records may describe one candidate.

**Ranks have gaps, and that is the point.** A preview exists for every selected
candidate, so its index carries ranks contiguous from 1. A clip exists only for
a candidate a person kept, so the ranks that survive rejection are a subset --
1, 4, 5, 9. They must stay strictly increasing, because that is the render
order, but demanding contiguity would mean either renumbering the clips (losing
the link back to the shortlist) or refusing every review that rejected
anything.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import Field, model_validator

from content_engine.domain.candidates import _Artifact, _close
from content_engine.domain.enums import ClipCategory, RenderPreset, ReviewDecisionType

#: Bumped whenever clips/index.json changes incompatibly. Version 2 added
#: ``metadata_sha256`` and ``metadata_size_bytes`` to every record: version 1
#: left ``metadata.json`` outside every digest, so a clip's topic, its
#: provenance fingerprints or the run it came from could be rewritten and the
#: set still reused. An index written by a version 1 build is refused rather
#: than reinterpreted, because it cannot answer the question this one asks.
RENDER_INDEX_SCHEMA_VERSION = 2
#: Bumped whenever clips/config.effective.json changes incompatibly.
RENDER_STAGE_CONFIG_SCHEMA_VERSION = 1
#: Bumped whenever a clip's metadata.json changes incompatibly.
CLIP_METADATA_SCHEMA_VERSION = 1
#: Bumped whenever the render policy changes what a clip contains. Lives here
#: rather than beside the rules because the index carries it as a default and
#: ``render_rules`` imports these models.
RENDER_RULES_VERSION = 1

#: One directory per clip, holding the four artifacts the specification names.
#: The candidate identifier is the only variable part, which is what makes the
#: mapping from a directory back to a candidate total and reversible.
CLIP_DIRNAME_TEMPLATE = "clip_{candidate_id}"
CLIP_FILENAME = "clip.mp4"
SUBTITLES_SRT_FILENAME = "subtitles.srt"
SUBTITLES_ASS_FILENAME = "subtitles.ass"
CLIP_METADATA_FILENAME = "metadata.json"

#: Characters a candidate identifier may contain before it becomes a directory
#: name. Identifiers are generated by CE-024 as ``cand_`` plus hex, so this
#: never rejects anything the engine produced; it rejects what an edited
#: artifact could contain, and a directory assembled from an untrusted string is
#: a traversal waiting to happen.
_SAFE_IDENTIFIER = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")

#: A measured duration is compared to the interval it claims, never equated to
#: it: the encoder ends on a frame boundary and the muxer rounds. The same 1.0 s
#: the preview stage uses, and for the same reason -- wide enough that it cannot
#: fail on a correct encode, narrow enough to catch a truncated or empty one.
#: The 15 real previews drifted at most 0.040 s.
RENDER_DURATION_TOLERANCE_SECONDS = 1.0

#: What ffprobe must report for the pixels to be square. Anything else means a
#: player will stretch the clip back out of 9:16.
EXPECTED_SAMPLE_ASPECT_RATIO = "1:1"

#: The two decisions that produce a clip. A rejection produces nothing, which is
#: enforced by the record refusing to hold that value at all rather than by the
#: service remembering to filter it out.
RENDERABLE_DECISIONS: frozenset[ReviewDecisionType] = frozenset(
    {ReviewDecisionType.APPROVED, ReviewDecisionType.EDITED}
)


def clip_dirname(candidate_id: str) -> str:
    """The directory one candidate's clip is written to, or a refusal.

    Raises rather than sanitising, exactly as ``preview_filename`` does. An
    identifier that is not safe to put in a path did not come from this engine,
    and quietly rewriting it would map two different candidates onto one
    directory.
    """
    if not candidate_id or not set(candidate_id) <= _SAFE_IDENTIFIER:
        raise ValueError(
            f"candidate identifier {candidate_id!r} is not safe to use in a directory name; "
            "expected only letters, digits, underscores and hyphens"
        )
    return CLIP_DIRNAME_TEMPLATE.format(candidate_id=candidate_id)


class RenderSubtitleConfig(_Artifact):
    """The subtitle rules and style one render ran under.

    Nested rather than flattened into the stage configuration because these are
    a coherent policy rather than a list of encoder switches: they are the
    answer to "what would this build produce from these words", and a reader
    comparing two runs wants to see the whole of it in one place.
    """

    #: What the cues were built from. One value today; named rather than implied
    #: so that a future segment-level fallback is a version bump and not a
    #: silent change of meaning.
    source: str = Field(min_length=1)
    max_words_per_cue: int = Field(gt=0)
    min_words_before_soft_break: int = Field(gt=0)
    max_lines: int = Field(gt=0)
    max_chars_per_line: int = Field(gt=0)
    pause_seconds: float = Field(gt=0)
    min_cue_seconds: float = Field(gt=0)

    font_name: str = Field(min_length=1)
    font_size: int = Field(gt=0)
    primary_colour: str = Field(min_length=1)
    outline_colour: str = Field(min_length=1)
    back_colour: str = Field(min_length=1)
    bold: bool
    outline: float = Field(ge=0)
    shadow: float = Field(ge=0)
    alignment: int = Field(ge=1, le=9)
    margin_horizontal: int = Field(ge=0)
    margin_vertical: int = Field(ge=0)


class RenderStageConfig(_Artifact):
    """``clips/config.effective.json``: what the render stage really ran.

    The readable counterpart of the stage fingerprint, following the shape the
    other three stages already use (ADR-017). The fingerprint decides whether a
    set of clips may be reused; this explains why, in terms a person can read
    without reversing a digest.

    Settings and versions only -- no path, no machine, no credential, and no
    identity belonging to one run. That is deliberate and it is what makes the
    digest answer a useful question: two runs rendered under the same policy
    have the same stage configuration digest, so a mismatch means the *policy*
    changed. Which material was rendered is the index's business.

    The encoder settings the specification puts in ``[render]`` come from the
    profile; the blur strength, the subtitle rules and the caption style are
    stage constants under ADR-028's reasoning -- they are not experiment
    variables, and putting them in the profile would fold them into
    ``config_sha256`` and change the logical identity of every existing run.
    They are recorded here in full regardless, because the stage still has to be
    able to say what produced its output.
    """

    schema_version: int = RENDER_STAGE_CONFIG_SCHEMA_VERSION

    width: int = Field(gt=0)
    height: int = Field(gt=0)
    preset: RenderPreset
    burn_subtitles: bool

    video_codec: str = Field(min_length=1)
    encoder_preset: str = Field(min_length=1)
    crf: int = Field(ge=0, le=51)
    pixel_format: str = Field(min_length=1)
    #: Gaussian blur sigma for the ``vertical_blur`` background. Recorded for
    #: both presets: ``vertical_crop`` ignores it, and a configuration that
    #: omitted it would make the two presets' digests differ for a reason that
    #: has nothing to do with the picture.
    blur_sigma: float = Field(ge=0)

    audio_codec: str = Field(min_length=1)
    audio_bitrate: str = Field(min_length=1)
    audio_sample_rate: int = Field(gt=0)
    audio_channels: int = Field(gt=0)

    #: What ffprobe must report for a clip to be accepted, which is not the same
    #: string as the encoder that produced it: libx264 writes h264.
    expected_video_codec: str = Field(min_length=1)
    expected_audio_codec: str = Field(min_length=1)
    expected_sample_aspect_ratio: str = Field(min_length=1)
    duration_tolerance_seconds: float = Field(gt=0)

    subtitles: RenderSubtitleConfig

    render_rules_version: int = Field(gt=0)
    #: Bumped independently of the rules: the same policy can be expressed by a
    #: different argument list, and an argument list change alters the bytes.
    argument_version: int = Field(gt=0)
    subtitle_rules_version: int = Field(gt=0)
    index_schema_version: int = Field(gt=0)
    metadata_schema_version: int = Field(gt=0)
    #: The candidate and decision schemas these clips were cut under, so a set
    #: can never be read as though it described a different generation of either.
    candidates_schema_version: int = Field(gt=0)
    decisions_schema_version: int = Field(gt=0)

    @model_validator(mode="after")
    def validate_dimensions(self) -> RenderStageConfig:
        for name, value in (("width", self.width), ("height", self.height)):
            if value % 2 != 0:
                raise ValueError(f"render {name} ({value}) must be even for H.264 encoding")
        return self


class ClipRecord(_Artifact):
    """One rendered clip and its two subtitle files, as measured afterwards."""

    candidate_id: str = Field(min_length=1)
    #: The candidate's rank, kept so the shortlist position survives into the
    #: output. Never renumbered: rank 4 with ranks 2 and 3 rejected is the
    #: honest record of what happened.
    rank: int = Field(ge=1)
    decision: ReviewDecisionType
    original_start: float = Field(ge=0)
    original_end: float = Field(gt=0)
    #: The interval actually rendered: the original for an approval, the
    #: reviewer's bounds for an edit. There is no third source.
    start: float = Field(ge=0)
    end: float = Field(gt=0)
    duration: float = Field(gt=0)

    directory: str = Field(min_length=1)
    clip_filename: str = Field(min_length=1)
    srt_filename: str = Field(min_length=1)
    ass_filename: str = Field(min_length=1)
    metadata_filename: str = Field(min_length=1)

    width: int = Field(gt=0)
    height: int = Field(gt=0)
    sample_aspect_ratio: str = Field(min_length=1)
    measured_duration_seconds: float = Field(gt=0)
    video_codec: str = Field(min_length=1)
    #: Not optional, unlike a preview record's. A silent clip is not publishable
    #: and the inspect stage already refuses a source without audio, so a null
    #: here would be a record of a defect rather than of a clip.
    audio_codec: str = Field(min_length=1)

    sha256: str = Field(min_length=64, max_length=64)
    size_bytes: int = Field(gt=0)
    srt_sha256: str = Field(min_length=64, max_length=64)
    srt_size_bytes: int = Field(ge=0)
    ass_sha256: str = Field(min_length=64, max_length=64)
    ass_size_bytes: int = Field(gt=0)
    #: The metadata document beside the clip. It is digested like the other
    #: three artifacts and for the same reason: without this, every field of
    #: ``metadata.json`` that the index does not separately duplicate could be
    #: rewritten without the set becoming unusable. There is no cycle -- the
    #: metadata is written first and hashed afterwards, so it never contains
    #: its own digest.
    metadata_sha256: str = Field(min_length=64, max_length=64)
    metadata_size_bytes: int = Field(gt=0)
    #: Zero is legitimate: an interval with no speech in it produces an empty
    #: SRT and an ASS holding only its header.
    cue_count: int = Field(ge=0)
    subtitles_burned: bool

    @model_validator(mode="after")
    def validate_record(self) -> ClipRecord:
        self._validate_interval()
        self._validate_names()
        self._validate_decision()
        drift = abs(self.measured_duration_seconds - self.duration)
        if drift > RENDER_DURATION_TOLERANCE_SECONDS:
            raise ValueError(
                f"the clip for {self.candidate_id} measured {self.measured_duration_seconds}s "
                f"for a {self.duration}s interval, {drift:.3f}s beyond the "
                f"{RENDER_DURATION_TOLERANCE_SECONDS}s tolerance"
            )
        return self

    def _validate_interval(self) -> None:
        if self.end <= self.start:
            raise ValueError(
                f"the clip for {self.candidate_id} ends at {self.end}, at or before its start"
            )
        if self.original_end <= self.original_start:
            raise ValueError(
                f"the clip for {self.candidate_id} records an original interval ending at "
                f"{self.original_end}, at or before its start"
            )
        if not _close(self.duration, self.end - self.start):
            raise ValueError(
                f"the clip for {self.candidate_id} declares duration {self.duration} for the "
                f"interval [{self.start}, {self.end}]"
            )

    def _validate_names(self) -> None:
        if self.directory != clip_dirname(self.candidate_id):
            raise ValueError(
                f"directory {self.directory!r} does not name candidate {self.candidate_id}"
            )
        for field, expected in (
            ("clip_filename", CLIP_FILENAME),
            ("srt_filename", SUBTITLES_SRT_FILENAME),
            ("ass_filename", SUBTITLES_ASS_FILENAME),
            ("metadata_filename", CLIP_METADATA_FILENAME),
        ):
            actual = getattr(self, field)
            if actual != expected:
                raise ValueError(f"{field} is {actual!r}; expected {expected!r}")

    def _validate_decision(self) -> None:
        """A clip may only exist for a decision that produced an interval.

        The check is not redundant with the service filtering rejections out.
        This model is read back off disk by a later invocation, and an index
        naming a rejected candidate is precisely the artifact that must not be
        believed: it would mean somebody's rejection had been rendered anyway.
        """
        if self.decision not in RENDERABLE_DECISIONS:
            raise ValueError(
                f"the clip for {self.candidate_id} records decision {self.decision}, which "
                f"approves no interval; only {', '.join(sorted(RENDERABLE_DECISIONS))} produce "
                "a clip"
            )
        moved = not _close(self.start, self.original_start) or not _close(
            self.end, self.original_end
        )
        if self.decision is ReviewDecisionType.APPROVED and moved:
            raise ValueError(
                f"the clip for {self.candidate_id} was approved but was rendered over "
                f"[{self.start}, {self.end}] rather than the proposed "
                f"[{self.original_start}, {self.original_end}]"
            )
        if self.decision is ReviewDecisionType.EDITED and not moved:
            raise ValueError(
                f"the clip for {self.candidate_id} is recorded as edited but was rendered over "
                f"the proposed [{self.original_start}, {self.original_end}]"
            )


class ClipMetadata(_Artifact):
    """``clips/clip_<id>/metadata.json``: one clip, described where it lives.

    Deliberately self-contained. The index is the engine's view of the whole
    stage; this travels with the three files beside it, so somebody handed one
    directory can say which candidate it is, which decision produced it, which
    seconds of which source it holds, and which analysis and review it came out
    of -- without the run it was cut from.

    Its **digest** is in the index, and the file itself is not, which is what
    keeps the two from chasing each other: the metadata is written, then hashed,
    and the hash goes into the record. So it never contains its own digest and
    is still covered by the render fingerprint.

    It is *also* parsed and compared against the record field by field. That is
    not redundant with the digest -- a digest proves the bytes have not moved,
    the comparison proves the two artifacts still say the same thing, and only
    the second would catch a set where both files were rewritten together.
    """

    schema_version: int = CLIP_METADATA_SCHEMA_VERSION
    generated_at: datetime
    run_id: str = Field(min_length=1)

    candidate_id: str = Field(min_length=1)
    rank: int = Field(ge=1)
    decision: ReviewDecisionType
    category: ClipCategory
    topic: str
    hook: str
    summary: str
    reason: str
    total_score: float = Field(ge=0, le=100)

    original_start: float = Field(ge=0)
    original_end: float = Field(gt=0)
    start: float = Field(ge=0)
    end: float = Field(gt=0)
    duration: float = Field(gt=0)

    preset: RenderPreset
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    sample_aspect_ratio: str = Field(min_length=1)
    video_codec: str = Field(min_length=1)
    audio_codec: str = Field(min_length=1)
    measured_duration_seconds: float = Field(gt=0)
    sha256: str = Field(min_length=64, max_length=64)
    size_bytes: int = Field(gt=0)
    srt_sha256: str = Field(min_length=64, max_length=64)
    ass_sha256: str = Field(min_length=64, max_length=64)
    cue_count: int = Field(ge=0)
    subtitles_burned: bool

    analysis_fingerprint: str = Field(min_length=64, max_length=64)
    review_fingerprint: str = Field(min_length=64, max_length=64)
    source_sha256: str = Field(min_length=64, max_length=64)
    transcript_sha256: str = Field(min_length=64, max_length=64)


class RenderIndex(_Artifact):
    """``clips/index.json``: every clip this run holds, and what it is.

    Carries the identity of everything it was built from -- the analysis, the
    review, the decisions, the transcript and the source -- rather than a path.
    A path says where a file was on one machine; a digest says whether it is the
    same file.
    """

    schema_version: int = RENDER_INDEX_SCHEMA_VERSION
    rules_version: int = RENDER_RULES_VERSION
    generated_at: datetime
    #: The analysis execution the candidates came from.
    analysis_fingerprint: str = Field(min_length=64, max_length=64)
    #: The completed review the decisions came from, and the digest of the
    #: decision file itself. Both, because the fingerprint proves the review was
    #: finished and the digest proves these are the bytes that finished it.
    review_fingerprint: str = Field(min_length=64, max_length=64)
    decisions_sha256: str = Field(min_length=64, max_length=64)
    #: The transcript the subtitles were built from. Nothing else in the render
    #: stage reads it, and a different transcript is different subtitles over
    #: identical video, which no other digest here would notice.
    transcript_sha256: str = Field(min_length=64, max_length=64)
    source_sha256: str = Field(min_length=64, max_length=64)
    source_duration_seconds: float = Field(gt=0)
    width: int = Field(gt=0)
    height: int = Field(gt=0)
    preset: RenderPreset
    burn_subtitles: bool
    clips: list[ClipRecord] = Field(default_factory=list)

    @model_validator(mode="after")
    def validate_index(self) -> RenderIndex:
        identifiers = [entry.candidate_id for entry in self.clips]
        repeated = sorted({name for name in identifiers if identifiers.count(name) > 1})
        if repeated:
            raise ValueError(f"candidate appears more than once: {', '.join(repeated)}")

        ranks = [entry.rank for entry in self.clips]
        if any(later <= earlier for earlier, later in zip(ranks, ranks[1:], strict=False)):
            raise ValueError(
                f"clips are not in strictly increasing rank order: {ranks}. Ranks may have "
                "gaps where a candidate was rejected, but never repeat or go backwards."
            )

        for entry in self.clips:
            if (entry.width, entry.height) != (self.width, self.height):
                raise ValueError(
                    f"the clip for {entry.candidate_id} is {entry.width}x{entry.height} in an "
                    f"index of {self.width}x{self.height} clips"
                )
            if entry.subtitles_burned != self.burn_subtitles:
                raise ValueError(
                    f"the clip for {entry.candidate_id} records subtitles_burned="
                    f"{entry.subtitles_burned} in an index that ran with "
                    f"burn_subtitles={self.burn_subtitles}"
                )
            if entry.end > self.source_duration_seconds + RENDER_DURATION_TOLERANCE_SECONDS:
                raise ValueError(
                    f"the clip for {entry.candidate_id} ends at {entry.end}, beyond the source "
                    f"duration ({self.source_duration_seconds})"
                )
        return self

    @property
    def by_candidate(self) -> dict[str, ClipRecord]:
        return {entry.candidate_id: entry for entry in self.clips}
